spring:
  datasource:
    url: jdbc:h2:./devdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistance:
          validation:
            mode: none